### ISSUE TITLE
Add Conv1D

### ISSUE THREAD

**Issue by BrendanMulcahy** [tcmxx/UnityTensorflowKeras#2]
Conv1D is left unimplemented (presumably because it was not added in the original TFSharp repo).  How difficult would this be to add to your TFSharp/KerasSharp/Unity repos?

I could try to do the work and submit a PR.  I'm interested in trying to do a temporal convolutional network (TCN) in place of an RNN.

Thoughts?

**Comment by tcmxx** [comment]
It should not be too hard to add conv1D. We use a [fork of KerasSharp](https://github.com/tcmxx/keras-sharp) as the backend and because that repo is stopped so Conv1D is not implemented. The implementation should be similar to the conv2D implementation here:https://github.com/tcmxx/keras-sharp/blob/master/Sources/Layers/Convolutional/Conv2D.cs.
